travis:
  secure:
    BINSTAR_TOKEN: b/I7C1Gwa451RiSqp91ubHzePWx+j+skuRCVDWmWwgOFlLrw5RG+loUyFt+ijVX5tqrEBlnU8EO9l1hcl9VELhFfuDClHvrtqSXk5145KKIojSTWGIl0B9QjiHRqRe12S5kkLktWpWzoZ0zrbRAB0B94zMDg0wEESEeI5b0oBTLeXXPpxIEc4AKaeRvd/ep8haYtfxkKGn0z0Z6ui7fEdT4qdlZMdp9ifBf2kvnV5bZHHZymh5QjamOaJ12XiYHeME4HS5oQ51IXxKNDAbPyCzdtOHrcZVl6Bppd2mSP00Xz2Ft+dBjHTss7B7Ux4wfz5DOvE8TLECiJF09tZ2LK7ALGM/x0gXG1xVkQpRSMxCU23D8XBlJZ6LvTaa2Srn+R7VnKtRDOqlrXorZJUWCgSW+wMa95PFoSzOXOFE0qbD8dsZUMMTHu2/A4XM5j05FmpxYf1ighVZ+yncgkMR5uzaM9f3pjbvXrMN598Ss67OVVY5mHxuLriSEiIP/D9+rGbn0Vh0DuqBzO0i8CNwMJIUO+ol+6JQ0G0GsQAiXLg3Cz/h7pRHjWKNYI8M/APC3Iodl0xnWo7yJSdRMqnyn0o33xv2GGZ6j7Wdywf013Km7MaOMFe6boJxdtckDHsNeeeoQWPpbOCQt7tV3VMYM+VqOjL0rdXsuhYBxttwNjPlE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
