travis:
  secure:
    BINSTAR_TOKEN: VUEHvbq27kigskjAP1DZVZQOJzvnTHLf8CTwvbfvFoQD5X66G5STtrxJaTTgyCsSnGcHG82mYuA9fCfUror+O/TJLOtMiCoatXOxu6c71ddCPFhi8oQd/p0Hz88XA8l4NwvJADjgn5l4WzmC2mxD78HJtH4jW2RkqhHsnHEB8ODbpupPRjHfmyyFQ7YgBU3rHCziuSoo/TySfAp4EobXUYuJYwt2VNLEDpEmx2vFOzd7JykmNfggLEUh2GsP5oy4B5NZTip+Twfo9SYrVg3mK7PmRDoXKMzzLL5v+/WJld6BND4pkaiRJlEKs+tOzISOLy8ikvWRm/MZO5QcFjbxuYjb0nYMxggiTSsZ0L/X5DHEFuW0e5ID6lme2acjxRIE9bkOaBjgyt72/zo5MI4cr4ZbogwfrklIuEafuDx9eeGge7kt6BrsyUUzYxI0b6FbKoMC0vdWX9kfbCuMzUhEHiWlMhHXEE7pPe2J6GXOhv60or1EcPKWtVCvZdZlyGWGkqSOv5BHB1X9eifLtfyCk9syl9qURfhpThLvRBX3LeWws/z974/j0tj7jSAFGotdQUJk8pXT3jtRx2NfxVaTXsPMHGDg8+d82cUaA8IYcyP9JRAm3Nug7JExXm63Vxeek4G3ow34nx8YVO4ee1oK6cVKTgq2PudO1oXWMPoWYIA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
